### ISSUE TITLE
Time Picker Component

### ISSUE THREAD

**Issue by Polarts** [Polarts/feel-tracker#3]
I need a really good time picker component for the app.
The idea is something like Android's clock-styled time picker.

I've looked at [react-gradient-timepicker](https://github.com/rahuldhawani/react-gradient-timepicker), but it doesn't work with newer versions of React and doesn't support TS.

You can either help by forking [react-gradient-timepicker](https://github.com/rahuldhawani/react-gradient-timepicker), fixing its errors and adding types, or making your own open-source time picker component that I'll use in the app.

Other similar time pickers for reference:
[jquery-clock-timepicker](https://github.com/loebi-ch/jquery-clock-timepicker)
[ClockPicker](https://github.com/weareoutman/clockpicker)

**Comment by Roman253** [comment]
Will try
